Repository openteamsinc/closember, pull requests merged in 2022-11, with the labels that each got.

#39 ENH - Add plausible script
  page.tpl
Labels: type: enhancement

#38 📄 Add license file
  LICENSE
  README.md
  page.tpl
Labels: type: maintenance

#42 Add templating and copy for after-Closember version of page
  page.tpl
Labels: type: enhancement, area: content
